-- CreateEnum
CREATE TYPE "public"."Role" AS ENUM ('USER', 'ADMIN');

-- CreateTable
CREATE TABLE "public"."USER" (
    "USER_ID" TEXT NOT NULL,
    "Email" TEXT NOT NULL,
    "Firstname" TEXT NOT NULL,
    "Lastname" TEXT NOT NULL,
    "Password" TEXT NOT NULL,
    "role" "public"."Role" NOT NULL DEFAULT 'USER',

    CONSTRAINT "USER_pkey" PRIMARY KEY ("USER_ID")
);

-- CreateTable
CREATE TABLE "public"."POST" (
    "POST_ID" TEXT NOT NULL,
    "Title" TEXT NOT NULL,
    "Slug" TEXT NOT NULL,
    "Content" TEXT NOT NULL,
    "Image_url" TEXT,
    "published" BOOLEAN NOT NULL DEFAULT false,
    "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP(3) NOT NULL,
    "USER_ID" TEXT NOT NULL,

    CONSTRAINT "POST_pkey" PRIMARY KEY ("POST_ID")
);

-- CreateTable
CREATE TABLE "public"."COMMENT" (
    "COMMENT_ID" TEXT NOT NULL,
    "Content" TEXT NOT NULL,
    "CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "POST_ID" TEXT NOT NULL,
    "USER_ID" TEXT NOT NULL,

    CONSTRAINT "COMMENT_pkey" PRIMARY KEY ("COMMENT_ID")
);

-- CreateTable
CREATE TABLE "public"."POST_CATEGORY" (
    "POST_ID" TEXT NOT NULL,
    "CATEGORY_ID" TEXT NOT NULL,

    CONSTRAINT "POST_CATEGORY_pkey" PRIMARY KEY ("POST_ID","CATEGORY_ID")
);

-- CreateTable
CREATE TABLE "public"."CATEGORY" (
    "CATEGORY_ID" TEXT NOT NULL,
    "Name" TEXT NOT NULL,

    CONSTRAINT "CATEGORY_pkey" PRIMARY KEY ("CATEGORY_ID")
);

-- CreateTable
CREATE TABLE "public"."POST_TAG" (
    "POST_ID" TEXT NOT NULL,
    "TAG_ID" TEXT NOT NULL,

    CONSTRAINT "POST_TAG_pkey" PRIMARY KEY ("POST_ID","TAG_ID")
);

-- CreateTable
CREATE TABLE "public"."TAG" (
    "TAG_ID" TEXT NOT NULL,
    "Name" TEXT NOT NULL,

    CONSTRAINT "TAG_pkey" PRIMARY KEY ("TAG_ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USER_Email_key" ON "public"."USER"("Email");

-- CreateIndex
CREATE UNIQUE INDEX "POST_Slug_key" ON "public"."POST"("Slug");

-- CreateIndex
CREATE UNIQUE INDEX "CATEGORY_Name_key" ON "public"."CATEGORY"("Name");

-- CreateIndex
CREATE UNIQUE INDEX "TAG_Name_key" ON "public"."TAG"("Name");

-- AddForeignKey
ALTER TABLE "public"."POST" ADD CONSTRAINT "POST_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "public"."USER"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."COMMENT" ADD CONSTRAINT "COMMENT_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "public"."POST"("POST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."COMMENT" ADD CONSTRAINT "COMMENT_USER_ID_fkey" FOREIGN KEY ("USER_ID") REFERENCES "public"."USER"("USER_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."POST_CATEGORY" ADD CONSTRAINT "POST_CATEGORY_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "public"."POST"("POST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."POST_CATEGORY" ADD CONSTRAINT "POST_CATEGORY_CATEGORY_ID_fkey" FOREIGN KEY ("CATEGORY_ID") REFERENCES "public"."CATEGORY"("CATEGORY_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."POST_TAG" ADD CONSTRAINT "POST_TAG_POST_ID_fkey" FOREIGN KEY ("POST_ID") REFERENCES "public"."POST"("POST_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."POST_TAG" ADD CONSTRAINT "POST_TAG_TAG_ID_fkey" FOREIGN KEY ("TAG_ID") REFERENCES "public"."TAG"("TAG_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
